{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "1680d740_23b6ee27",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 16
      },
      "lineNbr": 0,
      "author": {
        "id": 1000056
      },
      "writtenOn": "2023-09-13T12:09:54Z",
      "side": 1,
      "message": "The CI failure is unrelated\n",
      "revId": "a14f3c2937a9505b50cca4e41860ae8a25be3c25",
      "serverId": "8f6f209b-db1a-4cbf-aa44-c8bc30e9bfda"
    }
  ]
}